# Generated by Django 5.1.2 on 2024-10-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P_S_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SorP', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('mr_mh_no', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=30)),
                ('unit_of_measure', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(null=True)),
                ('supplier_name', models.CharField(max_length=30)),
                ('project_no', models.CharField(max_length=30)),
                ('invoice_no', models.CharField(max_length=30)),
            ],
        ),
    ]
