# Generated by Django 5.1.2 on 2024-10-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('P_quantity', models.IntegerField(null=True)),
                ('S_quantity', models.IntegerField(null=True)),
                ('stock_quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
