# Generated by Django 5.1.2 on 2024-10-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_s_info',
            name='SorP',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='p_s_info',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
