# Generated by Django 5.1.2 on 2024-11-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0004_p_s_info_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_s_info',
            name='SorP',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('stock_Movement', 'Stock Movement')], max_length=50),
        ),
    ]
