# Generated by Django 5.1.2 on 2024-11-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0005_alter_p_s_info_sorp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_s_info',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='p_s_info',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
