# Generated by Django 5.1.2 on 2024-11-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0006_alter_p_s_info_date_alter_p_s_info_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock',
        ),
    ]
